language: node_js
node_js:
        - "8"

before_deploy: yarn build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js